apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: python-test
spec:
  selector:
    app: python-svc
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
